
email: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
domain: ""

exclude: [src, node_modules, package*, Gemfile*]

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Site navigation - each item must have a label and a url.
navigation:
  - text: Team
    url: /team/
  - text: Updates
    url: /updates/

# Colours
theme_color: '#326A85'
accent_color: '#326A85'
text_color: '#0A0908'
link_color: '#3E81A3'

t:
  en:
    title: Site title
    description: "Describe your site"
    language: English
    root: /en
    welcome: Welcome to
  cy:
    title: Teitl y safle
    description: "Describe your site"
    language: Cymraeg
    root: /cy
    welcome: Croeso i

